### ISSUE TITLE
Trezor `Qubes OS` wiki update

### ISSUE THREAD

**Issue by lunarthegrey** [trezor/trezord-go#180]
I'm not sure where else to put this issue as I'm not seeing a way to submit PRs to edit the wiki. I recently ran into an issue where I could not update `qubes-core-agent` due to the process spawned from this method on the Trezor wiki https://wiki.trezor.io/Qubes_OS

I'd like to propose a change to the wiki and have it as;

`socat TCP-LISTEN:21325,fork EXEC:"qrexec-client-vm sys-usb trezord-service" &`

Instead of..

`socat TCP-LISTEN:21325,fork EXEC:"qrexec-client-vm sys-usb trezord-service"`

Without the `&` as described by lead Qubes OS dev, it hangs rc.local https://github.com/QubesOS/qubes-issues/issues/5376#issuecomment-570974215

This pretty much breaks core Qubes OS packages from being upgraded. Can someone on the Trezor team update this? I've tested it as described here and it seems to work fine. https://github.com/QubesOS/qubes-issues/issues/5376#issuecomment-570975708

**Comment by prusnak** [comment]
Thank you. Fixed in the wiki (the change will propagate in 30 minutes)

**Comment by chaywoo** [comment]
![Add atTheEnd](https://user-images.githubusercontent.com/24528863/72194633-52dbd780-33c3-11ea-9e35-9eca2ee48c98.jpg)
LoL I hope I am not insulting anybody's intelligence, but I think I might be missing a step.

**Comment by prusnak** [comment]
@chaywoo you are missing `"`on the last line just before the `&`

**Comment by chaywoo** [comment]
@prusnak Thanks so much, I tried again, however, the screen sits waiting for me to do something with "-- INSERT --" at the bottom, so I tried control-c and insert went away, Debian9 updated successfully and the down arrow is gone now, but I still get the hang up (second pic) and im not sure if I saved the entry's using Cntrl-C correctly. Should I be posting this in a different location? I dont want to clog up your nice clean work.. Thanks
![trezord](https://user-images.githubusercontent.com/24528863/72212155-cfd28400-348b-11ea-92b0-574b4cf489cd.jpg)
This page never goes away, I do a control-c and it says I am stopping some shell or something...

![grubbyDown](https://user-images.githubusercontent.com/24528863/72212156-d4973800-348b-11ea-9944-bac62d069f59.jpg)
Everything seems to be working fine, so this is something I think I can just hope disappears over time?
It shows up when I try to update debian9, but I just updated it successfully, so maybe it gets stuck because there is no update available? I appreciate any input or redirection to the Qubes-OS kindergarden romper room. Thanks!

**Comment by chaywoo** [comment]
it seems I am writing a file called rc.local, but maybe im just not saving it correctly.

**Comment by lunarthegrey** [comment]
@chaywoo, seems like you ran into the 'can't exit vim' meme. After you insert, you have to hit `esc` and type `:wq` at the bottom left which stands for `write quit`. Alternatively, you could just use the `nano` editor which is easier.

A bit confused though, it seems you're running the `socat` in dom0 which is not intended. It should look like this.

dom0:

```
[dom0@dom0 ~]$ cat /etc/qubes-rpc/policy/trezord-service
$anyvm $anyvm allow,user=trezord,target=sys-usb
```

sys-usb:

```
[user@sys-usb ~]$ cat /usr/local/etc/qubes-rpc/trezord-service
socat - TCP:localhost:21325
```

AppVM:

```
user@appvm:~$ cat /rw/config/rc.local
#!/bin/sh

# This script will be executed at every VM startup, you can place your own
# custom commands here. This includes overriding some configuration in /etc,
# starting services etc.

# Example for overriding the whole CUPS configuration:
#  rm -rf /etc/cups
#  ln -s /rw/config/cups /etc/cups
#  systemctl --no-block restart cups

socat TCP-LISTEN:21325,fork EXEC:"qrexec-client-vm sys-usb trezord-service" &
```

**Comment by chaywoo** [comment]
@lunarthegrey Thanks so much, I know time is very valuable and I really appreciate the great feedback. I will have some time to work on this, this weekend, however, I dont have a sys-usb. I think Dom0 is operating the USB controls.. I understand this method is not as secure, but I just wanted to get started with qubes-os and if I wanted maximum security from the beginning, I never would have been able to get started LoL.. Or maybe there is a sys-usb, but if there is, it is not visible in the qube manager list.. And the user@appvm:~$ ?... Would this be the debian9 template terminal window? Please, let me know at your convenience.. Thanks so much..

**Comment by prusnak** [comment]
@chaywoo Please ask in the Qubes OS community.

**Comment by chaywoo** [comment]
@prusnak oh i'm sorry, I wont take it personal if my comments are deleted, thanks for pointing the way...
